[workspace]
authors = ["Jesse Akes <akesjesse@gmail.com>"]
channels = ["conda-forge"]
name = "amath583"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
quarto = ">=1.6.43,<2"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.1,<4"
